# Generated by Django 4.0.3 on 2024-01-01 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditlog", "0014_logentry_cid"),
    ]

    operations = [
        # 복합 인덱스: timestamp + action (가장 일반적인 쿼리 패턴)
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS auditlog_logentry_timestamp_action_idx "
            "ON auditlog_logentry (timestamp DESC, action)",
            reverse_sql="DROP INDEX IF EXISTS auditlog_logentry_timestamp_action_idx"
        ),
        
        # 복합 인덱스: timestamp + content_type (특정 모델의 로그 조회)
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS auditlog_logentry_timestamp_content_type_idx "
            "ON auditlog_logentry (timestamp DESC, content_type_id)",
            reverse_sql="DROP INDEX IF EXISTS auditlog_logentry_timestamp_content_type_idx"
        ),
        
        # 복합 인덱스: timestamp + actor (특정 사용자의 로그 조회)
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS auditlog_logentry_timestamp_actor_idx "
            "ON auditlog_logentry (timestamp DESC, actor_id)",
            reverse_sql="DROP INDEX IF EXISTS auditlog_logentry_timestamp_actor_idx"
        ),
        
        # 부분 인덱스: 최근 데이터만 인덱싱 (예: 최근 1년)
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS auditlog_logentry_recent_idx "
            "ON auditlog_logentry (timestamp DESC) "
            "WHERE timestamp > NOW() - INTERVAL '1 year'",
            reverse_sql="DROP INDEX IF EXISTS auditlog_logentry_recent_idx"
        ),
    ]